#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@kcptun_luci[-1]
	add ucitrack kcptun_luci
	set ucitrack.@kcptun_luci[-1].init=kcptun_luci
	commit ucitrack
EOF

general=$(uci -q get kcptun_luci.@general[-1])

if [ -z "$general" ]; then
	uci -q add kcptun_luci general
fi

if [ ."$general" != ."general" ]; then
	uci -q batch <<-EOF >/dev/null
		rename kcptun_luci.@general[-1]="general"
		set kcptun_luci.general.server=""
		commit kcptun_luci
	EOF
fi

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
